# Generated by Django 2.2.1 on 2019-05-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGastos', '0002_auto_20190526_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=45, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(default=None, max_length=80, verbose_name='Nome'),
        ),
    ]
