# Generated by Django 2.2.1 on 2019-05-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGastos', '0004_categoria_relatorio_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[(0, 'Receita'), (1, 'Despesa')], max_length=50, verbose_name='Tipo'),
        ),
    ]
