# Generated by Django 2.2.1 on 2019-10-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGastos', '0005_auto_20190527_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relatorio',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('0', 'Receita'), ('1', 'Despesa')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
